### PR TITLE
This was my code. It's not from Kurisu.

### PR DESCRIPTION
**Pull request by LyricLy**

### CODE REVIEW

**Comment by LyricLy** [comment]
Hey.

**Comment by GriffinG1** [comment]
well with how much shit you took from kurisu, how would a difference be made? Anyways that code was supposed to be removed anyways, which I'm about to do

**Comment by LyricLy** [comment]
That's great, now the error output isn't escaped. Good man.

**Comment by LyricLy** [comment]
I guess it doesn't really matter, though. Your server is dead.

**Comment by GriffinG1** [comment]
Closer to I, unlike you, don't need the error output escaped.

**Comment by GriffinG1** [comment]
In addition, good luck trying to pull this shit in the future, here or on discord, as you've hit the point you got blocked. You sad, sad, man.

**Pull request closed without merging**
